"""empty message

Revision ID: 80097016f2e1
Revises: 3a150d6d014f
Create Date: 2023-11-10 20:59:45.790492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80097016f2e1'
down_revision = '3a150d6d014f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
